# Site settings
title: nipy.github.io
description: "nipy.github.io"
url: "nipy.github.io"
author:
  name: "nipy"
  email: "neuroimaging@python.org"
  url: "nipy.github.io"

# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /blog/:title
paginate: 8
paginate_path: /blog/page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
reverse: true

